### ISSUE TITLE
wininet/winhttp

### ISSUE THREAD

**Issue by kolomansell** [pastapojken/Fusion360WineInstaller#3]
After OS reinstall now those two libraries are not needed and are making installer freeze.
I do not get it...

**Comment by pastapojken** [comment]
Uh. Weird. Sorry for the late reply, I will look into it :) Been super busy, so might take a while...

**Comment by kolomansell** [comment]
> Uh. Weird. Sorry for the late reply, I will look into it :) Been super busy, so might take a while...

No problem at all ... just wanted to let you know. 

Btw. wine 4.12 breaks Fusion. Today got the update and the application behaves like you would run it on DX11. You have panels and stuff but modeling area s frozen. 
Downgraded to 4.11 and everything is fine.

**Comment by pastapojken** [comment]
Good to know, thanks! Unfortunately had to temporarily switch my machine to windows so won't be able to look into this for a couple of weeks :/

**Comment by kolomansell** [comment]
Oh I am sorry for your loss :(
That's ok. I just wanted to pass the info.

**Comment by pastapojken** [comment]
Yeah, it all works flawlessly for me after I remove wininet/winhttp ¯\\_(ツ)_/¯ 
Weirdly it works for me without issues with 4.12.... oh well x)
